// MSXgl | Raw files definitions generated by the Build tool

#define XAA_ZX0_SEG 	4
#define XAA_ZX0_REL 	0x0000
#define XAA_ZX0_ABS 	0x8000
#define XAA_ZX0_SIZE	0x0243

#define XAB_ZX0_SEG 	4
#define XAB_ZX0_REL 	0x0243
#define XAB_ZX0_ABS 	0x8243
#define XAB_ZX0_SIZE	0x0423

#define XAC_ZX0_SEG 	4
#define XAC_ZX0_REL 	0x0666
#define XAC_ZX0_ABS 	0x8666
#define XAC_ZX0_SIZE	0x01F1

#define PALETTE_BIN_SEG 	4
#define PALETTE_BIN_REL 	0x0857
#define PALETTE_BIN_ABS 	0x8857
#define PALETTE_BIN_SIZE	0x0020

#define PENGUIN_LVM_SEG 	5
#define PENGUIN_LVM_REL 	0x0000
#define PENGUIN_LVM_ABS 	0xA000
#define PENGUIN_LVM_SIZE	0x14CB

#define MM_DEVA_08_BIN_SEG 	6
#define MM_DEVA_08_BIN_REL 	0x0000
#define MM_DEVA_08_BIN_ABS 	0xC000
#define MM_DEVA_08_BIN_SIZE	0x9B17
